"""Run this project end to end, and write down that it ran.

A repository whose continuous integration is frozen says nothing about itself: the green tick
is two years old, or absent. What replaces it is ``reports/run-evidence.json`` — the exact
command, the day, the revision, the tool versions, what it cost, and the tracked files it
produced. A reader can rerun that command and compare.

**The run must reproduce what the repository publishes.** The steps below regenerate the key
outputs; if any of them comes out different from the committed version, no evidence is
written and the differing files are named. That is the whole value of the exercise: evidence
that merely says « it ran » proves that something ran, not that what is published is what it
produces.

    uv run python scripts/smoke.py

Run it on a clean clone, before the release tag. No workflow writes this file: a committed
artefact regenerated by continuous integration is an artefact whose author is a machine
nobody watches.
"""

from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess  # nosec B404 - local processes, constant argv
import sys
import tempfile
import time
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from rl_lander.utils.paths import DEFAULT_MODEL_PATH, ROOT_DIR, ROOT_ENV, SCRIPTS_DIR

EVIDENCE = "reports/run-evidence.json"
COMMAND = "uv run python scripts/smoke.py"

#: The two files the run has to produce identically, or the evidence is not written.
#:
#: The evaluation manifest is not among them, and cannot be: it dates the evaluation and
#: names the revision it ran at, so it differs from the committed one by design. What is
#: compared is what the published tables are read from.
KEY_OUTPUT: tuple[str, ...] = (
    "reports/evaluation_episodes.csv",
    "reports/evaluation_summary.json",
)

#: The distributions whose version changes the result. Not the whole lock file — the reader
#: needs what would explain a different number, not an inventory.
TOOLS: tuple[str, ...] = ("gymnasium", "stable-baselines3", "torch", "numpy", "Box2D")


def _run(*arguments: str, root: Path) -> None:
    """Call one of the scripts of `scripts/`, in its own process, and stop on a non-zero exit.

    Its output is printed whatever happens: a smoke run that fails silently has to leave the
    reader with the same lines they would have seen typing the command themselves.
    """
    print(f"[run] {' '.join(arguments)}")
    done = subprocess.run(  # nosec B603 - sys.executable, constant argv
        [sys.executable, *arguments],
        cwd=ROOT_DIR,
        env={**os.environ, "PYTHONIOENCODING": "utf-8", ROOT_ENV: str(root)},
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    print(done.stdout.rstrip())
    if done.returncode != 0:
        raise SystemExit(f"{arguments[0]} failed ({done.returncode}):\n{done.stderr}")


def steps() -> None:
    """The shipped policy, scored on the published grids, and the exports compared.

    This is the one published table a clean clone can rebuild. The five training runs behind
    the headline figure cost a million steps each and their directories are ignored by git;
    what is tracked is the checkpoint and what was measured from it, so what a smoke run can
    settle is whether that measurement still comes out the same. Six grids, 100 episodes
    each, deterministic actions: 600 landings, and two files that have to match byte for
    byte.

    The exporter writes into a temporary root, through ``RL_LANDER_ROOT``, and the two
    artefacts are then copied over the committed ones. Running it in place would rewrite the
    dated manifest as a side effect, and leave the checkout modified by a script whose whole
    point is to show that nothing moved.
    """
    with tempfile.TemporaryDirectory(prefix="rl-lander-smoke-") as scratch:
        elsewhere = Path(scratch)
        _run(
            str(SCRIPTS_DIR / "evaluate_and_export.py"),
            "--model",
            str(DEFAULT_MODEL_PATH),
            root=elsewhere,
        )
        for rel in KEY_OUTPUT:
            produced = elsewhere / rel
            if not produced.exists():
                raise SystemExit(f"the run produced no {rel}: nothing to compare")
            shutil.copyfile(produced, ROOT_DIR / rel)


# --- What the evidence records ----------------------------------------------


def _git(*arguments: str) -> str:
    done = subprocess.run(  # nosec B603 B607 - constant argv, built here
        ["git", *arguments], cwd=ROOT_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def tool_versions() -> dict[str, str]:
    versions = {"python": platform.python_version()}
    for name in TOOLS:
        try:
            versions[name] = version(name)
        except PackageNotFoundError:
            versions[name] = "not installed"
    for binary, arguments in (("uv", ("--version",)), ("docker", ("--version",))):
        if shutil.which(binary):
            done = subprocess.run([binary, *arguments], capture_output=True, text=True, check=False)  # nosec B603 - constant argv, built here
            versions[binary] = done.stdout.strip() or "unknown"
    return versions


def reproduced() -> list[str]:
    """The key outputs the run did NOT reproduce: missing, untracked, or changed."""
    problems: list[str] = []
    for rel in KEY_OUTPUT:
        if not (ROOT_DIR / rel).exists():
            problems.append(f"{rel} — not produced")
            continue
        if not _git("ls-files", "--error-unmatch", rel):
            problems.append(f"{rel} — produced but not tracked by git")
            continue
        if _git("status", "--porcelain", "--", rel):
            problems.append(f"{rel} — differs from the committed version")
    return problems


def main() -> int:
    if not KEY_OUTPUT:
        print("scripts/smoke.py: name the tracked files this run regenerates", file=sys.stderr)
        return 1

    started = time.monotonic()
    steps()
    duration = round(time.monotonic() - started, 1)

    differences = reproduced()
    if differences:
        print("the run did not reproduce what is published:", file=sys.stderr)
        for line in differences:
            print(f"  {line}", file=sys.stderr)
        print(f"{EVIDENCE} not written", file=sys.stderr)
        return 1

    evidence = {
        "command": COMMAND,
        "ran_at": datetime.now(tz=UTC).date().isoformat(),
        "git_revision": _git("rev-parse", "HEAD"),
        "tool_versions": tool_versions(),
        "duration_seconds": duration,
        "key_output": list(KEY_OUTPUT),
        # Null, and said so: the workflows of this repository are frozen to a manual trigger,
        # so there is no run to point at. A missing key would read as an oversight.
        "workflow_run_url": None,
    }
    target = ROOT_DIR / EVIDENCE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"{EVIDENCE} written — {duration}s, {len(KEY_OUTPUT)} output(s) reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
